name: Self-hosted Runner Pipeline

on: [push]

jobs:
  pipeline:
    runs-on: self-hosted  # Specify the label of your self-hosted runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Add your pipeline steps here
      - name: Npm Package Installation
        run: |
          npm install
      - name: Build VueJs App
        run: |
          npm run build
      - name: Copy Nginx Conf
        run: |
          cp -r .nginx/nginx.conf /etc/nginx/nginx.conf
          rm -rf /usr/share/nginx/html/*
      - name: Deploy of VueJs Application
        run: |
          cp -r dist /usr/share/nginx/html
          

